Repository FunStorageRoom/FunStorageRoom, pull requests merged in 2024-06, with the labels that each got.

#64 수화기 발광효과 설정
  Assets/Materials/New Material.mat
  Assets/Materials/New Material.mat.meta
  Assets/Materials/shine.mat
  Assets/Materials/shine.mat.meta
  Assets/Scenes/MainScene.unity
  Assets/lightening.cs
  Assets/lightening.cs.meta
  Assets/rotates.cs
Labels: Enhancement, Design

#65 Feature/#11
  Assets/Scenes/MainScene.unity
  Assets/lightening.cs
  Assets/phone.cs
  Assets/phone.cs.meta
  Assets/phonetrigger.cs
  Assets/phonetrigger.cs.meta
  Assets/rotates.cs
Labels: Enhancement

#66 Feature/#19-2 타자기 상호작용 추가
  Assets/Scenes/MainScene.unity
  Assets/TypeWriterBtnAction.cs
Labels: Enhancement

#69 손추가
  Assets/Scenes/MainScene.unity
Labels: Design

#70 Feature/#67
  Assets/CanvasResize.cs
  Assets/CanvasResize.cs.meta
  Assets/Scenes/MainScene.unity
  Assets/TypeWriterBtnAction.cs
  Assets/TypeWriterDisplay.cs
Labels: Enhancement
