Repository FunStorageRoom/FunStorageRoom, pull requests merged in 2024-05, with the labels that each got.

#50 Feat: 객체 설명판 추가 & 조명 설정 & 찬장 TV 배치 예시
  Assets/Scenes/SampleScene 1.unity
  Assets/danthaigames/DS 80s Television/Prefabs/80sTelevision.prefab
  Assets/light.cs
  Assets/light.cs.meta
Labels: Enhancement

#53 Feature/#12 타자기 인터렉션 로직 개발 - 타자기 타이핑 기능 구현
  Assets/Scenes/SampleScene 1.unity
  Assets/Scenes/TestScene.unity
  Assets/Scenes/TestScene1.unity
  Assets/TypeWriterBtnAction.cs
  Assets/TypeWriterBtnAction.cs.meta
  Assets/TypeWriterDisplay.cs
  Assets/TypeWriterDisplay.cs.meta
Labels: Enhancement

#55 Feat: 타자기 사운드 추가
  Assets/AudioClipManager.cs
  Assets/AudioClipManager.cs.meta
  Assets/Scenes/SampleScene 1.unity
  Assets/TypeWriterBtnAction.cs
Labels: bug, Enhancement

#61 Feature/#59
  Assets/Scenes/SampleScene 1.unity
  Assets/Scenes/TestScene.unity
Labels: Feature

#62 Feature/#18
  Assets/Scenes/SampleScene 1.unity
  Assets/XRI/Settings/Resources/XRDeviceSimulatorSettings.asset
  Assets/_Course Library/Scripts/Controls/XRKnob.cs
  Assets/dialrotate.cs
  Assets/dialrotate.cs.meta
  Assets/hinge.cs
  Assets/hinge.cs.meta
  Assets/rotate.cs
  Assets/rotate.cs.meta
  Assets/rotates.cs
  Assets/rotates.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Enhancement
